language: node_js
node_js:
- "7.4"
branches:
  only:
    - master
before_install:
- npm install
- git fetch origin gh-pages
- git status
script:
- npm run build
- git checkout -b travis-build
- cp -r dist/* .
- git add static index.html
- git status
