language: node_js
node_js:
- "7.4"
branches:
  only:
    - master
before_install:
- npm install
- git fetch origin gh-pages
- git status
script:
- npm run build
- git checkout -b travis-build
- find . -type f -not -name 'dist' -print0 | xargs -0 rm --
- cp -r dist/* .
- git status
- git add .
- git status
